package com.xe.demo.model;

import java.io.Serializable;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "supplier_master")
public class SupplierMaster implements Serializable {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.unit_code
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.unit_name
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.master_contacts
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String masterContacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.master_phone
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String masterPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.master_fax
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String masterFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.master_mail
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String masterMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_master.foller_persion
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private String follerPersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_master
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.id
     *
     * @return the value of supplier_master.id
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.id
     *
     * @param id the value for supplier_master.id
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.unit_code
     *
     * @return the value of supplier_master.unit_code
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.unit_code
     *
     * @param unitCode the value for supplier_master.unit_code
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.unit_name
     *
     * @return the value of supplier_master.unit_name
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.unit_name
     *
     * @param unitName the value for supplier_master.unit_name
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.master_contacts
     *
     * @return the value of supplier_master.master_contacts
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getMasterContacts() {
        return masterContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.master_contacts
     *
     * @param masterContacts the value for supplier_master.master_contacts
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setMasterContacts(String masterContacts) {
        this.masterContacts = masterContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.master_phone
     *
     * @return the value of supplier_master.master_phone
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getMasterPhone() {
        return masterPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.master_phone
     *
     * @param masterPhone the value for supplier_master.master_phone
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setMasterPhone(String masterPhone) {
        this.masterPhone = masterPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.master_fax
     *
     * @return the value of supplier_master.master_fax
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getMasterFax() {
        return masterFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.master_fax
     *
     * @param masterFax the value for supplier_master.master_fax
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setMasterFax(String masterFax) {
        this.masterFax = masterFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.master_mail
     *
     * @return the value of supplier_master.master_mail
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getMasterMail() {
        return masterMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.master_mail
     *
     * @param masterMail the value for supplier_master.master_mail
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setMasterMail(String masterMail) {
        this.masterMail = masterMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_master.foller_persion
     *
     * @return the value of supplier_master.foller_persion
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public String getFollerPersion() {
        return follerPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_master.foller_persion
     *
     * @param follerPersion the value for supplier_master.foller_persion
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    public void setFollerPersion(String follerPersion) {
        this.follerPersion = follerPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_master
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SupplierMaster other = (SupplierMaster) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUnitCode() == null ? other.getUnitCode() == null : this.getUnitCode().equals(other.getUnitCode()))
            && (this.getUnitName() == null ? other.getUnitName() == null : this.getUnitName().equals(other.getUnitName()))
            && (this.getMasterContacts() == null ? other.getMasterContacts() == null : this.getMasterContacts().equals(other.getMasterContacts()))
            && (this.getMasterPhone() == null ? other.getMasterPhone() == null : this.getMasterPhone().equals(other.getMasterPhone()))
            && (this.getMasterFax() == null ? other.getMasterFax() == null : this.getMasterFax().equals(other.getMasterFax()))
            && (this.getMasterMail() == null ? other.getMasterMail() == null : this.getMasterMail().equals(other.getMasterMail()))
            && (this.getFollerPersion() == null ? other.getFollerPersion() == null : this.getFollerPersion().equals(other.getFollerPersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_master
     *
     * @mbg.generated Mon Sep 11 15:16:40 GMT+08:00 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUnitCode() == null) ? 0 : getUnitCode().hashCode());
        result = prime * result + ((getUnitName() == null) ? 0 : getUnitName().hashCode());
        result = prime * result + ((getMasterContacts() == null) ? 0 : getMasterContacts().hashCode());
        result = prime * result + ((getMasterPhone() == null) ? 0 : getMasterPhone().hashCode());
        result = prime * result + ((getMasterFax() == null) ? 0 : getMasterFax().hashCode());
        result = prime * result + ((getMasterMail() == null) ? 0 : getMasterMail().hashCode());
        result = prime * result + ((getFollerPersion() == null) ? 0 : getFollerPersion().hashCode());
        return result;
    }
}