package com.xe.demo.model;

import java.io.Serializable;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "supplier_contacts")
public class SupplierContacts implements Serializable {
    
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
 
    private String name;
 
    private String title;
 
    private String dept;
 
    private String phone;
 
    private String fax;
 
    private String homeTel;
 
    private String unitTel;
 
    private String qqWx;
 
    private String zipcode;
 
    private String remark;
   
    private Integer masterId;
 
    private static final long serialVersionUID = 1L;
 
    public Integer getId() {
        return id;
    }

   
    public void setId(Integer id) {
        this.id = id;
    }
 
    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }
 
    public String getTitle() {
        return title;
    }
 
    public void setTitle(String title) {
        this.title = title;
    }

    
    public String getDept() {
        return dept;
    }

   
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.phone
     *
     * @return the value of supplier_contacts.phone
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.phone
     *
     * @param phone the value for supplier_contacts.phone
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.fax
     *
     * @return the value of supplier_contacts.fax
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.fax
     *
     * @param fax the value for supplier_contacts.fax
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.home_tel
     *
     * @return the value of supplier_contacts.home_tel
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getHomeTel() {
        return homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.home_tel
     *
     * @param homeTel the value for supplier_contacts.home_tel
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.unit_tel
     *
     * @return the value of supplier_contacts.unit_tel
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getUnitTel() {
        return unitTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.unit_tel
     *
     * @param unitTel the value for supplier_contacts.unit_tel
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setUnitTel(String unitTel) {
        this.unitTel = unitTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.qq_wx
     *
     * @return the value of supplier_contacts.qq_wx
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getQqWx() {
        return qqWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.qq_wx
     *
     * @param qqWx the value for supplier_contacts.qq_wx
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setQqWx(String qqWx) {
        this.qqWx = qqWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.zipcode
     *
     * @return the value of supplier_contacts.zipcode
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.zipcode
     *
     * @param zipcode the value for supplier_contacts.zipcode
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.remark
     *
     * @return the value of supplier_contacts.remark
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.remark
     *
     * @param remark the value for supplier_contacts.remark
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.master_id
     *
     * @return the value of supplier_contacts.master_id
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.master_id
     *
     * @param masterId the value for supplier_contacts.master_id
     *
     * @mbg.generated Tue Sep 12 14:50:44 GMT+08:00 2017
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

}